### ISSUE TITLE
Deepsec UI crashes on initialisation

### ISSUE THREAD

**Issue by rkunnema** [DeepSec-prover/deepsec#82]
On MacOS 10.15.7, Deepsec GUI 1.0.0-rc3 crashes after the animation and while it displays "Initialization". The three dots are animated, but nothing happens.

When called from the command line, the following output is produced:
```
❯ /Applications/DeepSec\ UI.app/Contents/MacOS/DeepSec\ UI
09:44:29.689 [browser] warn - Not in production mode (current env: production)
Uncaught (in promise) Error: Invalid header: Does not start with Cr24
    at /Applications/DeepSec UI.app/Contents/Resources/app.asar/background.js:10:73579
    at /Applications/DeepSec UI.app/Contents/Resources/app.asar/background.js:10:73808
    at Z (/Applications/DeepSec UI.app/Contents/Resources/app.asar/background.js:10:160675)
    at D (/Applications/DeepSec UI.app/Contents/Resources/app.asar/background.js:10:157906)
    at /Applications/DeepSec UI.app/Contents/Resources/app.asar/background.js:10:159840
    at s (/Applications/DeepSec UI.app/Contents/Resources/app.asar/background.js:10:158044)
    at processTicksAndRejections (internal/process/task_queues.js:82:9)
```

**Comment by rkunnema** [comment]
BTW on MacOS 12.1., the bug does not seem to exist.
